name: 'Get Conan'
description: 'Installs Conan'
author: 'TurtleBrowser'
inputs:
  version:
    description: "Wanted conan version"
    required: false
    default: ''
outputs:
  version:
    description: "The version of Conan which was installed"
    value: ${{ steps.output_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install and update setup tools
      run: |
        /Library/Frameworks/Python.framework/Versions/3.11/bin/python -m pip install --upgrade pip
        pip3 install wheel setuptools
      shell: bash
    - name: Install conan latest
      if: ${{ inputs.version == '' }}
      run: pip3 install conan --upgrade
      shell: bash
    - name: Install conan version ${{ inputs.version }}
      if: ${{ inputs.version != '' }}
      run: pip3 install conan==${{ inputs.version }} --upgrade
      shell: bash
    - name: Fix path on Linux
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
        echo "${HOME}/Library/Python/3.11/bin" >> $GITHUB_PATH
        echo "${HOME}"
        echo "${HOME}/Library"
        echo "${HOME}/Python"
      shell: bash
    - name: Fill in output variable
      id: output_version
      shell: bash
      run: |
        conan --version
        echo "::set-output name=version::$(conan --version)"
branding:
  icon: "archive"
  color: "green"




